### PR TITLE
Landon/not json 3

### PR DESCRIPTION
**Pull request by landon-boone2001**
Added Basic Server functionality in C language, allowing for a client to send/receive a message to a server, and receive a response.

### CODE REVIEW

**Comment by jacksonmowry** [comment]
Is this already in the helloplus directory?

**Review by jacksonmowry — CHANGES_REQUESTED** [review]
I believe this is the same contribution from the helloplus assignment. Correct me if I'm wrong

**Comment by landon-boone2001** [comment]
Different to the helloplus assignment, although I had initially pushed this code to my hello fork earlier. that was a bare-bones server that uses Window's WinSock headers to open open a port. I created a new set of programs, Client/ServerTest.c, along with a Server header and Server.c that allows for transmission of messages between the server and the Client as a skeleton for future use in creating server calls

**Comment by jacksonmowry** [comment]
Sure, but what I moved was your helloplus assignment. We can duplicate the server into another directory, I just wanted to make sure your helloplus was in the correct spot. I'd say we can place your code under the directory `server/c`

If you move that whole directory on your branch and then we merge my changes we shouldn't run into any conflicts

**Pull request closed without merging**
